//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.RegistrySerialization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistrySerializationLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrySerializationLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tools.RegistrySerialization.RegistrySerializationLocalization", typeof(RegistrySerializationLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot deserialize the instance of &apos;{0}&apos; class because it wasn&apos;t serialized!.
        /// </summary>
        public static string ClassWasNotSerailized {
            get {
                return ResourceManager.GetString("ClassWasNotSerailized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot serialize the instance of &apos;{0}&apos; class because it does not support &apos;{1}&apos; attribute!.
        /// </summary>
        public static string NoRegistryDataContractAttribute {
            get {
                return ResourceManager.GetString("NoRegistryDataContractAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot serialize properties of &apos;{0}&apos; class because they do not support &apos;{1}&apos; attribute!.
        /// </summary>
        public static string NoRegistryDataMemberAttribute {
            get {
                return ResourceManager.GetString("NoRegistryDataMemberAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot serialize a property of type &apos;{0}&apos;!.
        /// </summary>
        public static string WrongPropertyType {
            get {
                return ResourceManager.GetString("WrongPropertyType", resourceCulture);
            }
        }
    }
}
